### ISSUE TITLE
Build fails: error in build.sh?

### ISSUE THREAD

**Issue by glubsy** [Deathamns/Viewhance#20]
When running `sh build.sh` or `./build.sh` I get these errors: 
```
build.sh: 4: build.sh: Bad substitution
build.sh: 10: build.sh: Syntax error: "(" unexpected
```
When running `bash build.sh` I get these errors:
```
Traceback (most recent call last):
  File "build_meta.py", line 245, in <module>
    fromlist=['build_meta']
ImportError: No module named crx.build_meta
build/crx: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
cp: cannot create regular file ‘/background.html’: Permission denied
cp: cannot create directory ‘/css’: Permission denied
cp: cannot create regular file ‘/defaults.json’: Permission denied
cp: cannot create regular file ‘/icon-18.png’: Permission denied
cp: cannot create regular file ‘/icon.png’: Permission denied
cp: cannot create directory ‘/includes’: Permission denied
cp: cannot create directory ‘/js’: Permission denied
cp: cannot create regular file ‘/options.html’: Permission denied
cp: cannot create regular file ‘/includes/’: Not a directory
cp: cannot create regular file ‘/js/’: Not a directory
build.sh: line 40: /includes/app.js: No such file or directory
Files ready: 
build/mxaddon: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
cp: cannot create regular file ‘/background.html’: Permission denied
cp: cannot create directory ‘/css’: Permission denied
cp: cannot create regular file ‘/defaults.json’: Permission denied
cp: cannot create regular file ‘/icon-18.png’: Permission denied
cp: cannot create regular file ‘/icon.png’: Permission denied
cp: cannot create directory ‘/includes’: Permission denied
cp: cannot create directory ‘/js’: Permission denied
cp: cannot create regular file ‘/options.html’: Permission denied
cp: cannot create regular file ‘/includes/’: Not a directory
cp: cannot create regular file ‘/js/’: Not a directory
cp: cannot create directory ‘/icons’: Permission denied
build.sh: line 40: /includes/app.js: No such file or directory
Files ready: 
build/oex: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
cp: cannot create regular file ‘/background.html’: Permission denied
cp: cannot create directory ‘/css’: Permission denied
cp: cannot create regular file ‘/defaults.json’: Permission denied
cp: cannot create regular file ‘/icon-18.png’: Permission denied
cp: cannot create regular file ‘/icon.png’: Permission denied
cp: cannot create directory ‘/includes’: Permission denied
cp: cannot create directory ‘/js’: Permission denied
cp: cannot create regular file ‘/options.html’: Permission denied
cp: cannot create regular file ‘/includes/’: Not a directory
cp: cannot create regular file ‘/js/’: Not a directory
build.sh: line 40: /includes/app.js: No such file or directory
Files ready: 
build/Viewhance.safariextension: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
cp: cannot create regular file ‘/background.html’: Permission denied
cp: cannot create directory ‘/css’: Permission denied
cp: cannot create regular file ‘/defaults.json’: Permission denied
cp: cannot create regular file ‘/icon-18.png’: Permission denied
cp: cannot create regular file ‘/icon.png’: Permission denied
cp: cannot create directory ‘/includes’: Permission denied
cp: cannot create directory ‘/js’: Permission denied
cp: cannot create regular file ‘/options.html’: Permission denied
cp: cannot create regular file ‘/includes/’: Not a directory
cp: cannot create regular file ‘/js/’: Not a directory
cp: cannot create regular file ‘/Settings.plist’: Permission denied
build.sh: line 40: /includes/app.js: No such file or directory
Files ready: 
build/xpi: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
cp: cannot create regular file ‘/background.html’: Permission denied
cp: cannot create directory ‘/css’: Permission denied
cp: cannot create regular file ‘/defaults.json’: Permission denied
cp: cannot create regular file ‘/icon-18.png’: Permission denied
cp: cannot create regular file ‘/icon.png’: Permission denied
cp: cannot create directory ‘/includes’: Permission denied
cp: cannot create directory ‘/js’: Permission denied
cp: cannot create regular file ‘/options.html’: Permission denied
cp: cannot create regular file ‘/includes/’: Not a directory
cp: target ‘/js/’ is not a directory
cp: cannot create regular file ‘/bootstrap.js’: Permission denied
build.sh: line 40: /includes/app.js: No such file or directory
Files ready: 
```

Running `sudo bash build.sh` (why do I even have to try that?) I get these errors:
```
Traceback (most recent call last):
  File "build_meta.py", line 245, in <module>
    fromlist=['build_meta']
ImportError: No module named crx.build_meta
build/crx: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
Files ready: 
build/mxaddon: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
Files ready: 
build/oex: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
Files ready: 
build/Viewhance.safariextension: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
Files ready: 
build/xpi: No such file or directory
/usr/bin/find: invalid argument `-delete' to `-mmin'
Files ready: 
```

Bash version:
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by glubsy** [comment]
I replaced line 93:
`python3 build_meta.py ${py_args[@]}
`
with 
`python3 build_meta.py ${py_args[@]}
`
It seems to work now (I have both python 2 and 3).
